### ISSUE TITLE
puppet_module_install excludes too much

### ISSUE THREAD

**Issue by alexjfisher** [puppetlabs/beaker#725]
Hi
I'd like to be able to do something like...

```puppet_module_install(:source => File.join(module_root, 'spec/fixtures/modules/functions'), :module_name => 'functions')```

... but, 'spec' is in the default PUPPET_MODULE_INSTALL_IGNORE and as a result, nothing gets scp'ed

I believe the ignore paths should only be used if they appear in the module being copied itself, and not if they appear earlier in the path.

**Comment by electrical** [comment]
I've done some digging when @alexjfisher mentioned it on IRC.
https://github.com/puppetlabs/beaker/blob/master/lib/beaker/host.rb#L390-L392 does a glob of all the potential directories and rejects anything that matches the ignore_re.
The issue with this is that the Regex is not specific enough and matches anything that is in the path.
So if you have a path called `/foo/bar/spec/something` it gets ignored because it has `spec` in the path name.
We should only process the ignoring of directories in the source dir it self.

A potential fix is to do `f.gsub(source, '') =~ ignore_re` at https://github.com/puppetlabs/beaker/blob/master/lib/beaker/host.rb#L391
which strips out the source path so we only evaluate the directories that are in the source path.

@anodelman any opinions on this?

**Comment by anodelman** [comment]
I think that our scp ignore is pretty much a mess and I'm going to be reviewing it this week.  The difficulty here is that some code depends upon our flexible attitude towards what is a match, yet, in this case, it is stabbing us in the back.

What really needs to happen here is better doc-ing that makes it clear what ignore does/doesn't do and then stick to i.

**Comment by anodelman** [comment]
A fix for this is actually included in https://github.com/puppetlabs/beaker/pull/730 - to only match against subdirs of the provided dir.

**Comment by anodelman** [comment]
PR merged.
